name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "**/*.tf"
      - ".github/workflows/release.yml"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    if: github.repository_owner == 'zleetch'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Release
        uses: cycjimmy/semantic-release-action@v4
        with:
          semantic_version: 24.0.0
          extra_plugins: |
            @semantic-release/changelog@6.0.3
            @semantic-release/git@10.0.1
            conventional-changelog-conventionalcommits@8.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
